// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProxySession(arg1, arg2) {
  return window['go']['main']['App']['CreateProxySession'](arg1, arg2);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetLocalIp() {
  return window['go']['main']['App']['GetLocalIp']();
}

export function GetWsServerStatus() {
  return window['go']['main']['App']['GetWsServerStatus']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartWsServer(arg1) {
  return window['go']['main']['App']['StartWsServer'](arg1);
}

export function StopWsServer() {
  return window['go']['main']['App']['StopWsServer']();
}
