// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<boolean>;

export function CreateProxySession(arg1:string,arg2:Record<string, string>):Promise<string>;

export function DeleteCacheBatch(arg1:Array<number>):Promise<number>;

export function DeleteCacheByID(arg1:number):Promise<boolean>;

export function DeleteCachedFile(arg1:string):Promise<boolean>;

export function DownloadVideo(arg1:string,arg2:Record<string, string>,arg3:string):Promise<string>;

export function DownloadVideoWithMeta(arg1:string,arg2:Record<string, string>,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string):Promise<string>;

export function FindDownloadRecordByFilePath(arg1:string):Promise<Record<string, any>>;

export function FindNextCachedEpisode(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function GetCacheDir():Promise<string>;

export function GetCacheProgress(arg1:string):Promise<Record<string, any>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetCachedFile(arg1:string):Promise<string>;

export function GetClients():Promise<Array<Record<string, any>>>;

export function GetDownloadProgress(arg1:string):Promise<Record<string, any>>;

export function GetDownloadQueue():Promise<Array<Record<string, any>>>;

export function GetLocalIp():Promise<string>;

export function GetLocalIps():Promise<Array<string>>;

export function GetPlayHistory():Promise<Array<Record<string, any>>>;

export function GetProxyPort():Promise<number>;

export function GetSelectedLanIp():Promise<string>;

export function GetWsServerStatus():Promise<Record<string, any>>;

export function ListCachedFiles():Promise<Array<Record<string, any>>>;

export function ListCachedFilesPaged(arg1:number,arg2:number,arg3:string,arg4:string):Promise<Record<string, any>>;

export function RetryDownload(arg1:string):Promise<boolean>;

export function SaveCacheProgress(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function SavePlayHistory(arg1:main.PlayHistoryEntry):Promise<boolean>;

export function SelectCacheDir():Promise<string>;

export function SendMessage(arg1:string,arg2:number,arg3:any):Promise<boolean>;

export function SetCacheDir(arg1:string):Promise<boolean>;

export function SetKeepScreenOn(arg1:boolean):Promise<void>;

export function SetSelectedLanIp(arg1:string):Promise<void>;

export function StartWsServer(arg1:number):Promise<boolean>;

export function StopWsServer():Promise<boolean>;
