// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProxySession(arg1:string,arg2:Record<string, string>):Promise<string>;

export function GetClients():Promise<Array<Record<string, any>>>;

export function GetLocalIp():Promise<string>;

export function GetWsServerStatus():Promise<Record<string, any>>;

export function SendMessage(arg1:string,arg2:number,arg3:any):Promise<boolean>;

export function StartWsServer(arg1:number):Promise<boolean>;

export function StopWsServer():Promise<boolean>;
