// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProxySession(arg1, arg2) {
  return window['go']['main']['WindowApp']['CreateProxySession'](arg1, arg2);
}

export function DeleteCachedFile(arg1) {
  return window['go']['main']['WindowApp']['DeleteCachedFile'](arg1);
}

export function DeleteCacheBatch(arg1) {
  return window['go']['main']['WindowApp']['DeleteCacheBatch'](arg1);
}

export function DeleteCacheByID(arg1) {
  return window['go']['main']['WindowApp']['DeleteCacheByID'](arg1);
}

export function DownloadVideo(arg1, arg2, arg3) {
  return window['go']['main']['WindowApp']['DownloadVideo'](arg1, arg2, arg3);
}

export function GetCacheDir() {
  return window['go']['main']['WindowApp']['GetCacheDir']();
}

export function GetCacheStats() {
  return window['go']['main']['WindowApp']['GetCacheStats']();
}

export function GetCachedFile(arg1) {
  return window['go']['main']['WindowApp']['GetCachedFile'](arg1);
}

export function GetClients() {
  return window['go']['main']['WindowApp']['GetClients']();
}

export function GetDownloadProgress(arg1) {
  return window['go']['main']['WindowApp']['GetDownloadProgress'](arg1);
}

export function GetDownloadQueue() {
  return window['go']['main']['WindowApp']['GetDownloadQueue']();
}

export function GetLocalIp() {
  return window['go']['main']['WindowApp']['GetLocalIp']();
}

export function GetWsServerStatus() {
  return window['go']['main']['WindowApp']['GetWsServerStatus']();
}

export function ListCachedFiles() {
  return window['go']['main']['WindowApp']['ListCachedFiles']();
}

export function ListCachedFilesPaged(arg1, arg2, arg3) {
  return window['go']['main']['WindowApp']['ListCachedFilesPaged'](arg1, arg2, arg3);
}

export function CancelDownload(arg1) {
  return window['go']['main']['WindowApp']['CancelDownload'](arg1);
}

export function SelectCacheDir() {
  return window['go']['main']['WindowApp']['SelectCacheDir']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['WindowApp']['SendMessage'](arg1, arg2, arg3);
}

export function SetCacheDir(arg1) {
  return window['go']['main']['WindowApp']['SetCacheDir'](arg1);
}

export function StartWsServer(arg1) {
  return window['go']['main']['WindowApp']['StartWsServer'](arg1);
}

export function StopWsServer() {
  return window['go']['main']['WindowApp']['StopWsServer']();
}
